---
- name: Display the progress of this play
  ansible.builtin.debug:
    msg: "Processing {{ ansible_loop.index }}/{{ ansible_loop.length }}: {{ username }}"

- name: Kill any processes owned by the user account
  ansible.builtin.command: "pkill -u {{ username }}"
  register: pkill_result
  failed_when: pkill_result.rc > 1
  changed_when: false

- name: Remove user account
  ansible.builtin.user:
    name: "{{ username }}"
    state: absent
    remove: true
