---
- name: Display the progress of this play
  ansible.builtin.debug:
    msg: "Processing {{ ansible_loop.index }}/{{ ansible_loop.length }}: {{ username }}"

- name: Remove user account
  ansible.builtin.user:
    name: "{{ username }}"
    state: absent
    remove: true
