---
# This playbook should be executed from a managing node (most likely your localhost) to setup
# a Raspberry Pi as a development board for experimentation.
#
# Usage: this playbook can be run, as follows:
#
#    $ ./pw pdm run --venv in-project ansible-playbook servers.yml

- name: Configure basic server security
  hosts: unprovisioned_yoshimo
  become: true
  gather_facts: true
  tasks:
    - name: Import ansible-prep role
      ansible.builtin.import_role:
        name: ansible_prep

    - name: Import security role
      ansible.builtin.import_role:
        name: security

    - name: Import remove-account role
      ansible.builtin.import_role:
        name: remove_account

- name: Configure time synchronization server
  hosts: yoshimo
  become: true
  gather_facts: true
  tasks:
    - name: Import chrony role
      ansible.builtin.import_role:
        name: chrony
