---
- name: Import localadmin tasks
  ansible.builtin.import_tasks: localadmin.yml

- name: Import sudoers tasks
  ansible.builtin.import_tasks: sudoers.yml

- name: Import SSH tasks
  ansible.builtin.import_tasks: ssh.yml

- name: Import Fail2Ban tasks
  ansible.builtin.import_tasks: fail2ban.yml
  when: security_fail2ban_enabled | bool

- name: Import unattended upgrades tasks
  ansible.builtin.import_tasks: unattended_upgrades.yml
  when: security_unattended_upgrades_enabled | bool

- name: Import apt-listchanges tasks
  ansible.builtin.import_tasks: apt_listchanges.yml
  when: security_apt_listchanges_enabled | bool

- name: Import cleanup tasks
  ansible.builtin.import_tasks: cleanup.yml
  when: security_cleanup | bool
