---
- name: Include msmtp configuration
  ansible.builtin.include_tasks: msmtp.yml
  when: (security_msmtp_is_configured is not defined) or (not security_msmtp_is_configured | bool)

- name: Install mailx
  ansible.builtin.package:
    name: bsd-mailx
    state: present

- name: Add email configuration to unattended-upgrades
  ansible.builtin.blockinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    prepend_newline: true
    block: |
      Unattended-Upgrade::Mail "{{ security_unattended_upgrades_email_address }}";
      Unattended-Upgrade::MailReport "{{ security_unattended_upgrades_email_report }}";
    marker: "// {mark} ANSIBLE MANAGED BLOCK for Mail and MailOnlyOnError"
    mode: u=rw,g=r,o=r
  when: security_unattended_upgrades_email_address | length > 0
  notify: Validate unattended-upgrades configuration
