---
- name: Install unattended-upgrades
  ansible.builtin.package:
    name: unattended-upgrades
    state: present

- name: Copy unattended-upgrades files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  loop:
    - 50unattended-upgrades
    - 10periodic
  notify: Validate unattended-upgrades configuration

- name: Import unattended-upgrades email notifications configuration
  ansible.builtin.import_tasks: unattended_upgrades_email_notifications.yml
  when: security_unattended_upgrades_email_notifications | bool
